version: 2

models:
    - name: stg_users
      description: "Contains all the users and their data"
      columns:
          - name: user_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
      config:
        group: StgGrp
        meta:
          model_maturity: in dev
    - name: stg_orders
      description: "Contains the general order data without the items"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: user_id
            description: "User that did the order"
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: ref('stg_users')
                    field: user_id
          - name: status
            description: "Order status"
            data_tests:
              - accepted_values:
                  arguments:
                    # Aparte de estos la BD tiene 'Processing' y 'Shipped'
                    values: ['Complete', 'Cancelled', 'Returned']
      config:
        group: StgGrp
        meta:
          model_maturity: in dev
    - name: stg_order_items
      description: "list or items, one by one, that are part of an order"
      columns:
          - name: order_item_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: order_id
            description: "Order for which this item belongs"
            tests:
              # Unique se usa porque la cantidad esta en ordenes por lo que debe de ser unico de lo contrario la relacion no tiene sentido
              #- unique
              - not_null
              - relationships:
                  arguments:
                    to: ref('stg_orders')
                    field: order_id
          - name: product_id
            description: "Type of product of this item"
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: ref('stg_products')
                    field: product_id
      config:
        group: StgGrp
        meta:
          model_maturity: in dev
    - name: stg_products
      description: "Products and their data"
      columns:
        - name: product_id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
      config:
        group: StgGrp
        meta:
          model_maturity: in dev
