version: 2

sources:
  - name: thelook_ecommerce
    database: bigquery-public-data
    #schema: thelook_ecommerce
    tables:
      - name: order_items
      - name: orders
      - name: products
      - name: users
